### ISSUE TITLE
Activate hood-light

### ISSUE THREAD

**Issue by OberfragGER** [dna909/ioBroker.homeconnect#29]
Hi,

i have found various "button" but i miss the light-button.

At the moment you´ll have to activate the whole programm including the ventilator to activate the light.

Thanks in advance.

**Comment by TA2k** [comment]
did you try this option?
settings/Cooking.Common.Setting.Lighting

**Comment by OberfragGER** [comment]
yes. i switched from false to true... nothing happens.

**Comment by OberfragGER** [comment]
> did you try this option?
> settings/Cooking.Common.Setting.Lighting

Yes. of course.
Switched from false to true. Nothing happens.
even activated the power, set light to 100 and the flag to true... still nothing.

**Comment by TA2k** [comment]
can you put the instance with expert view in the log level debug.
And post the log when you put the lighting on true

**Comment by OberfragGER** [comment]
Hi,

i put the pastebin here:
https://pastebin.com/mjxji9mN

On top you see the try to put the flag on true...
The hood is BOSCH-DWK97JR60

I switched the light manually... state changes... but manipulation not possible.

**Comment by TA2k** [comment]
should be fixed with 0.0.26

**Comment by OberfragGER** [comment]
> should be fixed with 0.0.26

Im very sorry. i updated to 0.0.26 and its still not working. Checked it twice. Even tried to upload the adapter again.

I tried various settings. set light to true, without and with approvel, set the light dimmer to 100% and nothing happens.

I also tried to activate the hodd and then the light. still not possible. :(

Pastebin is here.
https://pastebin.com/4HfXENCv

Any suggestions.

**Comment by TA2k** [comment]
Can you please start the adapter wait 2min. delete the log
turn the lighting true and false without ack/bestätigung and send the log?

**Comment by OberfragGER** [comment]
> Can you please start the adapter wait 2min. delete the log
> turn the lighting true and false without ack/bestätigung
> Download the log and copy this content

Sorry for bothering you.
I confirm- its working now.
Here is the pastebin.
https://pastebin.com/T2HrLHsx

I think it was maybe the "missing" ack and maybe the waiting-time...

From my point of view- issue solved.

Thanks a lot for you work! I was very surprised of the very, very, fast fix.

best regards

**Comment by OberfragGER** [comment]
Okay. Solved.
Two ways possible.
1. I created two own datapoints and copied the status over (i did so)
2. choose "aktualisieren" instead of setstae.

Problem solved. Works flawless.

THX!
